version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"   
      - discovery.type=single-node   
    volumes: 
      - ~/.data/elasticsearch:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
      - 9300:9300
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '5'
  kibana:
    image: kibana:7.8.0
    ports:
      - "5601:5601"        

volumes:
  elasticsearch:
    driver: local
