version: '3'
services:
  billing-db:
    image: postgres:9.2
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT-3
    volumes:
      - "~/.data/postgres:/var/lib/postgresql/data"